name: riverpod_refresh
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.4
  riverpod_annotation: ^2.0.4
  dio: ^5.1.1
  auto_route: ^6.2.0
  google_nav_bar: ^5.0.6
  google_fonts: ^4.0.3
  flutter_spinkit: ^5.1.0
  flutter_animate: ^4.1.1+1
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: 2.1.5
  auto_route_generator: ^6.2.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
